version: '3' 
  services:
    dbt-bq-dtc:
      build:
        context: .
        dockerfile: ./dbt/Dockerfile.dbt
        target: dbt-bigquery
      image: dbt/bigquery
      volumes:
        - .:/usr/app
        - ~/.dbt/dbt-volume/:/root/.dbt/
        - ~/.google/credentials/google_credentials.json:/.google/credentials/google_credentials.json
      network_mode: host
    